All_Instruments_List = "./Data/Instruments/All Instruments"
Stocks_List = "./Data/Instruments/Stocks"
Stocks_List_Tracker = "./Data/Instruments/Tracker/tracker.csv"

Fundamental_Data_Update_Folder = "./Data/Fundamental/Updates"
Fundamental_Data_Production_Folder = "./Data/Fundamental/Production"
Fundamental_Data_Archived_Folder = "./Data/Fundamental/Archived"
Fundamental_Data_Failed_List = "./Data/Fundamental/Failed"

Daily_Data_Update_Folder = "./Data/Daily/Updates"
Daily_Data_Production_Folder = "./Data/Daily/Production"
Daily_Data_Archived_Folder = "./Data/Daily/Archived"
Daily_Data_Failed_List = "./Data/Daily/Failed"
Daily_Data_Tracker = "./Data/Daily/Tracker/tracker.csv"

Minute_Data_Update_Folder = "./Data/Minute/Updates"
Minute_Data_Production_Folder = "./Data/Minute/Production"
Minute_Data_Archived_Folder = "./Data/Minute/Archived"
Minute_Data_Failed_List = "./Data/Minute/Failed"
Minute_Data_Tracker = "./Data/Minute/Tracker/tracker.csv"
